# Generated by Django 2.0.3 on 2018-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
