# Generated by Django 2.0.3 on 2018-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('valid', 'valid'), ('invalid', 'invalid')], default='pending', max_length=30, verbose_name='status'),
        ),
    ]
