# Generated by Django 2.0.3 on 2018-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20180313_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abbs',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='abbs',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='abbs',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
