# Generated by Django 2.0.3 on 2018-04-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='country',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
    ]
