# Generated by Django 2.0.3 on 2018-04-20 18:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20180420_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contains',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
