# Generated by Django 2.0.3 on 2018-04-10 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20180409_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
