# Generated by Django 2.0.3 on 2018-04-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_contains'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tries',
            field=models.IntegerField(default=0),
        ),
    ]
