# Generated by Django 2.0.3 on 2018-04-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr',
            field=models.TextField(null=True),
        ),
    ]
