# Generated by Django 2.0.3 on 2018-03-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20180329_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='documents.Country'),
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='documents.Type'),
        ),
        migrations.AlterField(
            model_name='country',
            name='abbr',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='abbr',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('country', 'type', 'abbr')},
        ),
    ]
