# Generated by Django 2.0.3 on 2018-04-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20180329_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ref',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
